# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GenieflowTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    pod 'GoogleMaps'


  # Pods for GenieflowTest

  target 'GenieflowTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GenieflowTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
