# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoogleMapIntegration' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    pod 'GoogleMaps'

  # Pods for GoogleMapIntegration

  target 'GoogleMapIntegrationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
